<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml"> 
	<head>  
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
		<title>autofocus.cc</title>
		<?php echo $this->headLink()->appendStylesheet('/public/css/standard.css') ?>
	</head> 
	<body>
		<div id="header">
				<h1>autofocus.cc</h1>
		</div>
		<div id="content"> 
			<?php echo $this->layout()->content ?>
		</div>
		<div id="footer">
		</div>
	</body>
</html>
